# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_scherduler.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17server_scherduler.proto\".\n\x0fJobStateMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05JobID\x18\x02 \x01(\x05\"\x1f\n\x0bReplyResult\x12\x10\n\x08response\x18\x01 \x01(\t\"F\n\nJobCombine\x12\x11\n\tpartition\x18\x01 \x01(\x05\x12\x0e\n\x06JobIDs\x18\x02 \x03(\x05\x12\x15\n\rMPSPercentage\x18\x03 \x03(\x05\"5\n\x0fReplyPrediction\x12\x0e\n\x06JobIDs\x18\x01 \x03(\x05\x12\x12\n\nPrediction\x18\x02 \x03(\x02\"L\n\x0fLoadInformation\x12\x0e\n\x06GPU_ID\x18\x01 \x01(\x05\x12\r\n\x05GI_ID\x18\x02 \x01(\x05\x12\x0c\n\x04load\x18\x03 \x01(\x02\x12\x0c\n\x04name\x18\x04 \x01(\t\"/\n\x0eJobInformation\x12\x0e\n\x06GPU_ID\x18\x01 \x01(\x05\x12\r\n\x05JobID\x18\x02 \x01(\x05\"9\n\x0fNodeInformation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x32\xc4\x01\n\x10SchedulerService\x12,\n\x08JobState\x12\x10.JobStateMessage\x1a\x0c.ReplyResult\"\x00\x12,\n\tPredictor\x12\x0b.JobCombine\x1a\x10.ReplyPrediction\"\x00\x12(\n\x04Load\x12\x10.LoadInformation\x1a\x0c.ReplyResult\"\x00\x12*\n\x06Regist\x12\x10.NodeInformation\x1a\x0c.ReplyResult\"\x00\x32=\n\rWorkerService\x12,\n\tAccpetJob\x12\x0f.JobInformation\x1a\x0c.ReplyResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_scherduler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOBSTATEMESSAGE']._serialized_start=27
  _globals['_JOBSTATEMESSAGE']._serialized_end=73
  _globals['_REPLYRESULT']._serialized_start=75
  _globals['_REPLYRESULT']._serialized_end=106
  _globals['_JOBCOMBINE']._serialized_start=108
  _globals['_JOBCOMBINE']._serialized_end=178
  _globals['_REPLYPREDICTION']._serialized_start=180
  _globals['_REPLYPREDICTION']._serialized_end=233
  _globals['_LOADINFORMATION']._serialized_start=235
  _globals['_LOADINFORMATION']._serialized_end=311
  _globals['_JOBINFORMATION']._serialized_start=313
  _globals['_JOBINFORMATION']._serialized_end=360
  _globals['_NODEINFORMATION']._serialized_start=362
  _globals['_NODEINFORMATION']._serialized_end=419
  _globals['_SCHEDULERSERVICE']._serialized_start=422
  _globals['_SCHEDULERSERVICE']._serialized_end=618
  _globals['_WORKERSERVICE']._serialized_start=620
  _globals['_WORKERSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
